apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: i42lp0g34-java-springboot
  janus-idp.io/tekton: i42lp0g34-java-springboot
  backstage.io/kubernetes-id: i42lp0g34-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: i42lp0g34-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
